# version: '3'

# services:
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./certs:/etc/nginx/certs
#       - ./html:/usr/share/nginx/html
#     restart: always

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - ./certs:/etc/letsencrypt
#       - ./certbot/conf:/etc/letsencrypt
#       - ./html:/usr/share/nginx/html
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#     restart: unless-stopped

#   react-app:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     container_name: react-app
#     volumes:
#       - ./build:/app/build
#     restart: always
# version: '3'

# services:
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./certs:/etc/nginx/certs
#       - ./html:/usr/share/nginx/html
#     restart: always

#   react-app:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     container_name: react-app
#     volumes:
#       - ./build:/app/build
#     restart: always
version: '3'

services:

  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react-app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt/live/liyouyang.tech:/etc/nginx/certs
      - ./build:/usr/share/nginx/html
    restart: always

  

  
