version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
    depends_on:
      - certbot
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email lehuuuyn9999@gmail.com --agree-tos --no-eff-email -d liyouyang.tech -d www.liyouyang.tech
    networks:
      - web

networks:
  web:

