version: '3'
services:
  react-app:
    build: .
    ports:
      - "3000:3000"  # If you want to expose React development server
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/your_domain.com/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/your_domain.com/privkey.pem:/etc/nginx/certs/privkey.pem
    restart: always
